export const REQUEST_SUCCESS = "assignment/REQUEST_SUCCESS"
export const RESPONSE_ERROR = "assignment/RESPONSE_ERROR"
export const GET_ALL_QUESTIONS_SUCCESS = "assignment/GET_QUESTIONS_SUCCESS"
export const CREATE_QUESTION_SUCCESS= 'assignment/CREATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_SUCCESS= "assignment/UPDATE_QUESTION_SUCCESS"
export const EDIT_QUESTION_SUCCESS = "assignment/EDIT_QUESTION_SUCCESS"
export const DELETE_QUESTION_SUCCESS= "assignment/DELETE_QUESTION_SUCCESS"
export const GET_MAPPING_SUCCESS ="assignment/GET_MAPPING_SUCCESS"